# Generated by Django 5.1 on 2024-10-03 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('country', models.CharField(default='Colombia', max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('city', models.CharField(default='No Data', max_length=100)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('team_secondary', models.CharField(blank=True, default='No data', max_length=100, null=True)),
                ('play_offline', models.BooleanField(default=True)),
                ('play_online', models.BooleanField(default=True)),
                ('main_character', models.CharField(max_length=100)),
                ('second_option_player', models.CharField(blank=True, max_length=100, null=True)),
                ('third_option_player', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.TextField(blank=True, null=True)),
                ('instagram', models.TextField(blank=True, null=True)),
                ('tiktok', models.TextField(blank=True, null=True)),
                ('user_startgg', models.CharField(blank=True, max_length=100, null=True)),
                ('code_startgg', models.CharField(blank=True, max_length=20, null=True)),
                ('url_startgg', models.URLField(blank=True, null=True)),
                ('url_smashdata', models.URLField(blank=True, null=True)),
                ('combined_teams', models.TextField(blank=True, null=True)),
                ('combined_characters', models.TextField(blank=True, null=True)),
                ('logo_team_1', models.TextField(blank=True, null=True)),
                ('logo_team_2', models.TextField(blank=True, null=True)),
                ('logo_main', models.TextField(blank=True, null=True)),
                ('logo_2', models.TextField(blank=True, null=True)),
                ('logo_3', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BDCS',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('display_score', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phase_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('event_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tournament_name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tournament_name', models.CharField(blank=True, max_length=255, null=True)),
                ('winner', models.CharField(blank=True, max_length=255, null=True)),
                ('attendees', models.IntegerField(blank=True, null=True)),
                ('zona', models.CharField(blank=True, max_length=255, null=True)),
                ('pais', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Colombia Tournament',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tournament')),
            ],
        ),
    ]
