# Generated by Django 5.1 on 2024-09-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_player_name_player_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='startgg_user',
            new_name='second_option_player',
        ),
        migrations.AddField(
            model_name='player',
            name='city',
            field=models.CharField(default='No Data', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='code_startgg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='combined_characters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='combined_teams',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(default='Colombia', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='logo_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='logo_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='logo_main',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='logo_team_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='logo_team_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='main_character',
            field=models.CharField(default='Colombia', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='play_offline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='play_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='secondary_team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='third_option_player',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='url_smashdata',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='url_startgg',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='user_startgg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='zone',
            field=models.CharField(default='Colombia', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=100),
        ),
    ]
