# Generated by Django 5.1 on 2024-09-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_startgg_user_player_second_option_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='set',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='set',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='set',
            name='startgg_user',
        ),
        migrations.RemoveField(
            model_name='set',
            name='team',
        ),
        migrations.AddField(
            model_name='set',
            name='display_score',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='event_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='phase_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='tournament_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
