# Generated by Django 5.1 on 2024-09-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_set_first_name_remove_set_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='name',
        ),
        migrations.AddField(
            model_name='tournament',
            name='attendees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ciudad',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateField(default='2022-01-01'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='direccion',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pais',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='region',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_name',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='url',
            field=models.URLField(default='NULL'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='zona',
            field=models.CharField(default='NULL', max_length=255),
        ),
    ]
