# Generated by Django 5.1 on 2024-09-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_tournament_name_tournament_attendees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='attendees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='ciudad',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='pais',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='region',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='winner',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='zona',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='tournament',
            table='Colombia Tournament',
        ),
    ]
