# Generated by Django 5.1 on 2024-09-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_tournament_attendees_alter_tournament_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='secondary_team',
            field=models.CharField(blank=True, default='No data', max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='player',
            table='BDCS',
        ),
    ]
